name              'deb_pkg_unautostart'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides a custom resource for suppressing Debian package autostart'
version           '2.1.16'
source_url        'https://github.com/sous-chefs/deb_pkg_unautostart'
issues_url        'https://github.com/sous-chefs/deb_pkg_unautostart/issues'
chef_version      '>= 15.3'

supports 'debian', '>= 12.0'
supports 'ubuntu', '>= 24.04'
