name              'deb_pkg_unautostart'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Stop deb packages from starting services'
version           '2.1.1'
source_url        'https://github.com/sous-chefs/deb_pkg_unautostart'
issues_url        'https://github.com/sous-chefs/deb_pkg_unautostart/issues'
chef_version      '>= 12.15'

supports 'debian'
supports 'ubuntu'
